# Generated by Django 3.0.3 on 2020-04-10 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cmc', models.IntegerField()),
                ('card_type', models.CharField(choices=[('L', 'Land'), ('C', 'Creature'), ('A', 'Artifact'), ('E', 'Enchantment'), ('P', 'Planeswalker'), ('I', 'Instant'), ('S', 'Sorcery')], default='L', max_length=1)),
                ('ability', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commander', models.CharField(max_length=100)),
                ('cards', models.ManyToManyField(to='main_app.Card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(to='main_app.Color'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
